### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by mimzivvimzi** [Cury-Sohoni-Lau/browsepad#25]
- [x]  Input verification and validation for signup/login
    - [x]  Password best practices for password strength
- [x]  Login / logout flow - way to stay logged in through multiple sessions
- [x]  Extracting metadata from webpage - the url, the title, anything else useful
    - [x]  Display this info to user
- [x]  Sharing a note with another account (editable)
- [x]  Sharable link (view only)
- [ ]  Improvements to UI - using material UI
- [ ] Color scheme / palette 
    - [ ]  For buttons, text, etc. standardized across app
- [x]  Basic note text editor - be able to add bullets, bold, italics, headers
    - Use markdown or something else
- [x]  Profile pictures for users

- [ ]  Sharable link
    - [ ]  Get it to work for non-registered users
    - [ ]  Put link in input box?
    - [ ]  Clicking on "get shareable link" automatically puts link into your clipboard
- [ ]  Get notification bubble working again consistently
- [ ]  Markdown text editor - how will normal users know how to use it?
    - [ ]  Checkbox for markdown that's auto disabled?
    - [ ]  Markdown preview button?
    - [ ]  "Markdown supported!"  ??
    - [ ]  Bigger space for editing
- [ ]  Use a material design system
    - [ ]  Color palette + typography system implemented
    - [ ]  For buttons, text, etc. standardized across app
